# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Realm', '~> 2.4.2'

  # Pods for Swift

  target 'SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
