# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swifter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.0'
  pod 'SWXMLHash', '~> 3.0.0'

  target 'SwifterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwifterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
