# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Objective-C' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Objective-C
  pod 'FDCategories', '~> 1.1.0'
  pod 'pop', '~> 1.0.9'



  target 'Objective-CTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Objective-CUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
